
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int NUMERO = 34;
  public static final int FUNCTION = 27;
  public static final int IGUALES = 11;
  public static final int LKEY = 17;
  public static final int MULT = 2;
  public static final int CONST = 28;
  public static final int NIGUALES = 22;
  public static final int RESTA = 5;
  public static final int LPAREN = 15;
  public static final int INT = 29;
  public static final int OUT = 23;
  public static final int RPAREN = 16;
  public static final int NOT = 14;
  public static final int AND = 13;
  public static final int MAYORQUE = 7;
  public static final int IGUAL = 6;
  public static final int IN = 24;
  public static final int OR = 12;
  public static final int BOOL = 30;
  public static final int DIV = 3;
  public static final int SUMA = 4;
  public static final int MAIN = 32;
  public static final int IF = 21;
  public static final int ID = 33;
  public static final int PUNTYCOMA = 26;
  public static final int EOF = 0;
  public static final int RKEY = 18;
  public static final int error = 1;
  public static final int COMA = 25;
  public static final int RETRN = 19;
  public static final int BOLEAN = 35;
  public static final int DECLARE = 31;
  public static final int MAYORIGU = 9;
  public static final int MENORQUE = 8;
  public static final int WHILE = 20;
  public static final int MENORIGU = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MULT",
  "DIV",
  "SUMA",
  "RESTA",
  "IGUAL",
  "MAYORQUE",
  "MENORQUE",
  "MAYORIGU",
  "MENORIGU",
  "IGUALES",
  "OR",
  "AND",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LKEY",
  "RKEY",
  "RETRN",
  "WHILE",
  "IF",
  "NIGUALES",
  "OUT",
  "IN",
  "COMA",
  "PUNTYCOMA",
  "FUNCTION",
  "CONST",
  "INT",
  "BOOL",
  "DECLARE",
  "MAIN",
  "ID",
  "NUMERO",
  "BOLEAN"
  };
}

