
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import parser.symbols.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\100\000\002\002\004\000\002\002\012\000\002\003" +
    "\004\000\002\003\005\000\002\003\002\000\002\023\004" +
    "\000\002\023\002\000\002\022\004\000\002\022\007\000" +
    "\002\022\005\000\002\022\011\000\002\022\011\000\002" +
    "\022\004\000\002\025\004\000\002\025\002\000\002\026" +
    "\005\000\002\026\004\000\002\026\007\000\002\026\005" +
    "\000\002\026\011\000\002\026\011\000\002\026\004\000" +
    "\002\024\003\000\002\024\003\000\002\004\013\000\002" +
    "\005\003\000\002\005\002\000\002\006\005\000\002\006" +
    "\002\000\002\007\006\000\002\007\002\000\002\010\006" +
    "\000\002\010\005\000\002\011\003\000\002\011\002\000" +
    "\002\012\003\000\002\012\003\000\002\013\004\000\002" +
    "\014\004\000\002\014\006\000\002\015\003\000\002\015" +
    "\003\000\002\015\003\000\002\015\005\000\002\015\004" +
    "\000\002\016\004\000\002\016\002\000\002\017\003\000" +
    "\002\017\003\000\002\017\003\000\002\017\003\000\002" +
    "\017\003\000\002\017\003\000\002\017\003\000\002\017" +
    "\003\000\002\017\003\000\002\017\003\000\002\017\003" +
    "\000\002\017\003\000\002\017\003\000\002\020\005\000" +
    "\002\021\003\000\002\021\005\000\002\021\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\004\041\004\001\002\000\004\023\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\014\024\ufffd\035\015\036\011\037\017\040\014\001" +
    "\002\000\014\024\ufffd\035\015\036\011\037\017\040\014" +
    "\001\002\000\006\037\017\040\014\001\002\000\004\034" +
    "\211\001\002\000\004\024\150\001\002\000\004\043\uffdd" +
    "\001\002\000\010\037\017\040\014\043\uffe7\001\002\000" +
    "\004\043\020\001\002\000\004\043\uffde\001\002\000\006" +
    "\010\022\034\uffdf\001\002\000\004\034\uffe0\001\002\000" +
    "\014\021\031\032\026\043\024\044\025\045\032\001\002" +
    "\000\004\034\uffe1\001\002\000\044\004\uffd9\005\uffd9\006" +
    "\uffd9\007\uffd9\011\uffd9\012\uffd9\013\uffd9\014\uffd9\015\uffd9" +
    "\016\uffd9\017\uffd9\020\uffd9\021\061\022\uffd9\030\uffd9\033" +
    "\uffd9\034\uffd9\001\002\000\042\004\uffd8\005\uffd8\006\uffd8" +
    "\007\uffd8\011\uffd8\012\uffd8\013\uffd8\014\uffd8\015\uffd8\016" +
    "\uffd8\017\uffd8\020\uffd8\022\uffd8\030\uffd8\033\uffd8\034\uffd8" +
    "\001\002\000\004\021\056\001\002\000\042\004\040\005" +
    "\044\006\037\007\047\011\043\012\042\013\050\014\045" +
    "\015\053\016\052\017\035\020\046\022\uffd3\030\051\033" +
    "\uffd3\034\uffd3\001\002\000\004\034\uffdc\001\002\000\014" +
    "\021\031\032\026\043\024\044\025\045\032\001\002\000" +
    "\042\004\uffd7\005\uffd7\006\uffd7\007\uffd7\011\uffd7\012\uffd7" +
    "\013\uffd7\014\uffd7\015\uffd7\016\uffd7\017\uffd7\020\uffd7\022" +
    "\uffd7\030\uffd7\033\uffd7\034\uffd7\001\002\000\004\022\034" +
    "\001\002\000\042\004\040\005\044\006\037\007\047\011" +
    "\043\012\042\013\050\014\045\015\053\016\052\017\035" +
    "\020\046\022\uffd3\030\051\033\uffd3\034\uffd3\001\002\000" +
    "\014\021\uffc7\032\uffc7\043\uffc7\044\uffc7\045\uffc7\001\002" +
    "\000\014\021\031\032\026\043\024\044\025\045\032\001" +
    "\002\000\014\021\uffd0\032\uffd0\043\uffd0\044\uffd0\045\uffd0" +
    "\001\002\000\014\021\uffd2\032\uffd2\043\uffd2\044\uffd2\045" +
    "\uffd2\001\002\000\010\022\uffda\033\uffda\034\uffda\001\002" +
    "\000\014\021\uffcd\032\uffcd\043\uffcd\044\uffcd\045\uffcd\001" +
    "\002\000\014\021\uffce\032\uffce\043\uffce\044\uffce\045\uffce" +
    "\001\002\000\014\021\uffd1\032\uffd1\043\uffd1\044\uffd1\045" +
    "\uffd1\001\002\000\014\021\uffcb\032\uffcb\043\uffcb\044\uffcb" +
    "\045\uffcb\001\002\000\014\021\uffc6\032\uffc6\043\uffc6\044" +
    "\uffc6\045\uffc6\001\002\000\014\021\uffcf\032\uffcf\043\uffcf" +
    "\044\uffcf\045\uffcf\001\002\000\014\021\uffcc\032\uffcc\043" +
    "\uffcc\044\uffcc\045\uffcc\001\002\000\014\021\uffc9\032\uffc9" +
    "\043\uffc9\044\uffc9\045\uffc9\001\002\000\014\021\uffc8\032" +
    "\uffc8\043\uffc8\044\uffc8\045\uffc8\001\002\000\014\021\uffca" +
    "\032\uffca\043\uffca\044\uffca\045\uffca\001\002\000\010\022" +
    "\uffd4\033\uffd4\034\uffd4\001\002\000\010\022\uffdb\033\uffdb" +
    "\034\uffdb\001\002\000\004\022\057\001\002\000\042\004" +
    "\uffd6\005\uffd6\006\uffd6\007\uffd6\011\uffd6\012\uffd6\013\uffd6" +
    "\014\uffd6\015\uffd6\016\uffd6\017\uffd6\020\uffd6\022\uffd6\030" +
    "\uffd6\033\uffd6\034\uffd6\001\002\000\042\004\uffd5\005\uffd5" +
    "\006\uffd5\007\uffd5\011\uffd5\012\uffd5\013\uffd5\014\uffd5\015" +
    "\uffd5\016\uffd5\017\uffd5\020\uffd5\022\uffd5\030\uffd5\033\uffd5" +
    "\034\uffd5\001\002\000\016\021\031\022\uffc2\032\026\043" +
    "\024\044\025\045\032\001\002\000\006\022\uffc4\033\065" +
    "\001\002\000\004\022\064\001\002\000\042\004\uffc5\005" +
    "\uffc5\006\uffc5\007\uffc5\011\uffc5\012\uffc5\013\uffc5\014\uffc5" +
    "\015\uffc5\016\uffc5\017\uffc5\020\uffc5\022\uffc5\030\uffc5\033" +
    "\uffc5\034\uffc5\001\002\000\016\021\031\022\uffc2\032\026" +
    "\043\024\044\025\045\032\001\002\000\004\022\uffc3\001" +
    "\002\000\004\043\071\001\002\000\004\043\uffe8\001\002" +
    "\000\004\021\072\001\002\000\010\022\uffe5\037\017\040" +
    "\014\001\002\000\004\022\103\001\002\000\004\043\075" +
    "\001\002\000\006\022\uffe3\033\077\001\002\000\004\022" +
    "\uffe6\001\002\000\006\037\017\040\014\001\002\000\004" +
    "\043\101\001\002\000\006\022\uffe3\033\077\001\002\000" +
    "\004\022\uffe4\001\002\000\004\023\104\001\002\000\026" +
    "\003\113\024\ufff3\025\106\026\105\027\111\031\115\036" +
    "\011\037\017\040\014\043\112\001\002\000\004\021\142" +
    "\001\002\000\014\021\031\032\026\043\024\044\025\045" +
    "\032\001\002\000\026\003\113\024\ufff3\025\106\026\105" +
    "\027\111\031\115\036\011\037\017\040\014\043\112\001" +
    "\002\000\004\034\136\001\002\000\004\021\130\001\002" +
    "\000\006\010\022\021\061\001\002\000\004\034\123\001" +
    "\002\000\004\024\122\001\002\000\004\021\116\001\002" +
    "\000\014\021\031\032\026\043\024\044\025\045\032\001" +
    "\002\000\004\022\120\001\002\000\004\034\121\001\002" +
    "\000\026\003\ufff0\024\ufff0\025\ufff0\026\ufff0\027\ufff0\031" +
    "\ufff0\036\ufff0\037\ufff0\040\ufff0\043\ufff0\001\002\000\014" +
    "\024\uffe9\035\uffe9\036\uffe9\037\uffe9\040\uffe9\001\002\000" +
    "\026\003\uffec\024\uffec\025\uffec\026\uffec\027\uffec\031\uffec" +
    "\036\uffec\037\uffec\040\uffec\043\uffec\001\002\000\004\034" +
    "\uffeb\001\002\000\004\034\uffea\001\002\000\004\034\127" +
    "\001\002\000\026\003\uffef\024\uffef\025\uffef\026\uffef\027" +
    "\uffef\031\uffef\036\uffef\037\uffef\040\uffef\043\uffef\001\002" +
    "\000\014\021\031\032\026\043\024\044\025\045\032\001" +
    "\002\000\004\022\132\001\002\000\004\023\133\001\002" +
    "\000\026\003\113\024\ufff3\025\106\026\105\027\111\031" +
    "\115\036\011\037\017\040\014\043\112\001\002\000\004" +
    "\024\135\001\002\000\026\003\uffed\024\uffed\025\uffed\026" +
    "\uffed\027\uffed\031\uffed\036\uffed\037\uffed\040\uffed\043\uffed" +
    "\001\002\000\026\003\ufff1\024\ufff1\025\ufff1\026\ufff1\027" +
    "\ufff1\031\ufff1\036\ufff1\037\ufff1\040\ufff1\043\ufff1\001\002" +
    "\000\004\024\ufff4\001\002\000\004\034\141\001\002\000" +
    "\026\003\ufff2\024\ufff2\025\ufff2\026\ufff2\027\ufff2\031\ufff2" +
    "\036\ufff2\037\ufff2\040\ufff2\043\ufff2\001\002\000\014\021" +
    "\031\032\026\043\024\044\025\045\032\001\002\000\004" +
    "\022\144\001\002\000\004\023\145\001\002\000\026\003" +
    "\113\024\ufff3\025\106\026\105\027\111\031\115\036\011" +
    "\037\017\040\014\043\112\001\002\000\004\024\147\001" +
    "\002\000\026\003\uffee\024\uffee\025\uffee\026\uffee\027\uffee" +
    "\031\uffee\036\uffee\037\uffee\040\uffee\043\uffee\001\002\000" +
    "\004\042\151\001\002\000\004\023\152\001\002\000\024" +
    "\003\161\024\ufffb\026\153\027\156\031\162\036\011\037" +
    "\017\040\014\043\160\001\002\000\004\021\203\001\002" +
    "\000\004\024\202\001\002\000\004\034\201\001\002\000" +
    "\004\021\173\001\002\000\024\003\161\024\ufffb\026\153" +
    "\027\156\031\162\036\011\037\017\040\014\043\160\001" +
    "\002\000\006\010\022\021\061\001\002\000\004\034\167" +
    "\001\002\000\004\021\163\001\002\000\014\021\031\032" +
    "\026\043\024\044\025\045\032\001\002\000\004\022\165" +
    "\001\002\000\004\034\166\001\002\000\024\003\ufff9\024" +
    "\ufff9\026\ufff9\027\ufff9\031\ufff9\036\ufff9\037\ufff9\040\ufff9" +
    "\043\ufff9\001\002\000\024\003\ufff5\024\ufff5\026\ufff5\027" +
    "\ufff5\031\ufff5\036\ufff5\037\ufff5\040\ufff5\043\ufff5\001\002" +
    "\000\004\034\171\001\002\000\024\003\ufff8\024\ufff8\026" +
    "\ufff8\027\ufff8\031\ufff8\036\ufff8\037\ufff8\040\ufff8\043\ufff8" +
    "\001\002\000\004\024\ufffc\001\002\000\014\021\031\032" +
    "\026\043\024\044\025\045\032\001\002\000\004\022\175" +
    "\001\002\000\004\023\176\001\002\000\024\003\161\024" +
    "\ufffb\026\153\027\156\031\162\036\011\037\017\040\014" +
    "\043\160\001\002\000\004\024\200\001\002\000\024\003" +
    "\ufff6\024\ufff6\026\ufff6\027\ufff6\031\ufff6\036\ufff6\037\ufff6" +
    "\040\ufff6\043\ufff6\001\002\000\024\003\ufffa\024\ufffa\026" +
    "\ufffa\027\ufffa\031\ufffa\036\ufffa\037\ufffa\040\ufffa\043\ufffa" +
    "\001\002\000\004\002\000\001\002\000\014\021\031\032" +
    "\026\043\024\044\025\045\032\001\002\000\004\022\205" +
    "\001\002\000\004\023\206\001\002\000\024\003\161\024" +
    "\ufffb\026\153\027\156\031\162\036\011\037\017\040\014" +
    "\043\160\001\002\000\004\024\210\001\002\000\024\003" +
    "\ufff7\024\ufff7\026\ufff7\027\ufff7\031\ufff7\036\ufff7\037\ufff7" +
    "\040\ufff7\043\ufff7\001\002\000\014\024\ufffd\035\015\036" +
    "\011\037\017\040\014\001\002\000\004\024\ufffe\001\002" +
    "\000\004\043\214\001\002\000\006\010\022\034\uffdf\001" +
    "\002\000\004\034\uffe2\001\002\000\004\024\uffff\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\003\012\004\007" +
    "\010\011\012\015\001\001\000\012\003\215\004\007\010" +
    "\011\012\015\001\001\000\004\012\212\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\066\012\067\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\011\022\013\020\001\001\000\002\001\001\000" +
    "\006\014\027\015\026\001\001\000\002\001\001\000\004" +
    "\020\057\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\016\054\017\035\001\001\000\002\001\001\000\006" +
    "\014\032\015\026\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\016\040\017\035\001\001\000\002\001\001" +
    "\000\006\014\053\015\026\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\014\061\015\026\021\062\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\014\061\015\026\021\065\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\072\012\073\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\075\001\001\000\002\001\001\000\004" +
    "\012\077\001\001\000\002\001\001\000\004\007\101\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\010\107" +
    "\012\015\025\113\026\106\001\001\000\002\001\001\000" +
    "\006\014\137\015\026\001\001\000\012\010\107\012\015" +
    "\025\136\026\106\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\013\123\020\124\024\125\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\014" +
    "\116\015\026\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\130\015\026\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\010\107\012\015\025\133" +
    "\026\106\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\142\015\026\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\010\107\012\015\025\145" +
    "\026\106\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\010\154\012\015" +
    "\022\156\023\153\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\010\154" +
    "\012\015\022\156\023\171\001\001\000\010\013\123\020" +
    "\124\024\167\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\014\163\015\026\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\014" +
    "\173\015\026\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\010\154\012\015\022\156\023\176\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\203\015\026\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\010\154\012\015\022\156" +
    "\023\206\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\003\211\004\007\010\011\012\015\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\011\214\013\020\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INIT EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		SymbolInit start_val = (SymbolInit)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INIT ::= DECLARE LKEY DEF RKEY MAIN LKEY SENTENCIAS RKEY 
            {
              SymbolInit RESULT =null;
		 System.out.println("Inicio"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INIT",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // DEF ::= DFUNCION DEF 
            {
              SymbolDef RESULT =null;
		 System.out.println("DEF tipo 1"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DEF",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // DEF ::= DECLARACION PUNTYCOMA DEF 
            {
              SymbolDef RESULT =null;
		 System.out.println("DEF tipo 2"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DEF",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // DEF ::= 
            {
              SymbolDef RESULT =null;
		  System.out.println(" No mas declaraciones "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DEF",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTENCIAS ::= SENTENCIA SENTENCIAS 
            {
              Object RESULT =null;
		 System.out.println("Sentancia"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIAS",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIAS ::= 
            {
              Object RESULT =null;
		 System.out.println("No mas sentencias"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIAS",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= DECLARACION PUNTYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Declaracion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= OUT LPAREN EXPRESION RPAREN PUNTYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Ouput"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= ID SENTENCIA_ID PUNTYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Sentencia_ID "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= WHILE LPAREN EXPRESION RPAREN LKEY SENTENCIAS RKEY 
            {
              Object RESULT =null;
		 System.out.println("bucle while "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= IF LPAREN EXPRESION RPAREN LKEY SENTENCIAS RKEY 
            {
              Object RESULT =null;
		 System.out.println("Condicional "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= error PUNTYCOMA 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // R_SENTENCIAS ::= R_SENTENCIA R_SENTENCIAS 
            {
              Object RESULT =null;
		 System.out.println("R_Sentancia"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIAS",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // R_SENTENCIAS ::= 
            {
              Object RESULT =null;
		 System.out.println("No mas R_sentencias"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIAS",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // R_SENTENCIA ::= RETRN EXPRESION PUNTYCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  System.out.println("retorno "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIA",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // R_SENTENCIA ::= DECLARACION PUNTYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Declaracion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIA",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // R_SENTENCIA ::= OUT LPAREN EXPRESION RPAREN PUNTYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Ouput"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIA",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // R_SENTENCIA ::= ID SENTENCIA_ID PUNTYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Sentencia_ID "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIA",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // R_SENTENCIA ::= WHILE LPAREN EXPRESION RPAREN LKEY R_SENTENCIAS RKEY 
            {
              Object RESULT =null;
		 System.out.println("bucle while "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIA",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // R_SENTENCIA ::= IF LPAREN EXPRESION RPAREN LKEY R_SENTENCIAS RKEY 
            {
              Object RESULT =null;
		 System.out.println("Condicional "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIA",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // R_SENTENCIA ::= error PUNTYCOMA 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("R_SENTENCIA",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // SENTENCIA_ID ::= ASIGNACION 
            {
              Object RESULT =null;
		 System.out.println("Asignacio - Sentancia_ID"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA_ID",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // SENTENCIA_ID ::= FUNCION 
            {
              Object RESULT =null;
		 System.out.println("Funcion Sentancia_id"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA_ID",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // DFUNCION ::= FUNCTION RETURN ID LPAREN PARAMETRO RPAREN LKEY R_SENTENCIAS RKEY 
            {
              Object RESULT =null;
		 System.out.println("DECLARACION FUNCION "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DFUNCION",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // RETURN ::= TYPE 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RETURN",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // RETURN ::= 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RETURN",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // PARAMETRO ::= TYPE ID PARAMCONCAT 
            {
              Object RESULT =null;
		 System.out.println("Parametro "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PARAMETRO",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // PARAMETRO ::= 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PARAMETRO",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // PARAMCONCAT ::= COMA TYPE ID PARAMCONCAT 
            {
              Object RESULT =null;
		 System.out.println("Muchos parametros "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PARAMCONCAT",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // PARAMCONCAT ::= 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PARAMCONCAT",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // DECLARACION ::= CONST TYPE ID DECLAREND 
            {
              Object RESULT =null;
		 System.out.println("Constantes"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // DECLARACION ::= TYPE ID DECLAREND 
            {
              Object RESULT =null;
		 System.out.println("variable normal"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // DECLAREND ::= ASIGNACION 
            {
              Object RESULT =null;
		 System.out.println("asignamos"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DECLAREND",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // DECLAREND ::= 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DECLAREND",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // TYPE ::= INT 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TYPE",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // TYPE ::= BOOL 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TYPE",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // ASIGNACION ::= IGUAL EXPRESION 
            {
              Object RESULT =null;
		 System.out.println(" Asignacion "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // EXPRESION ::= VALOR OPERACION 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		System.out.println("Valor operacion : " + v); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // EXPRESION ::= LPAREN EXPRESION RPAREN OPERACION 
            {
              Object RESULT =null;
		 System.out.println("Parentesis expresion "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // VALOR ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("Nombre: " + id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VALOR",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // VALOR ::= NUMERO 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = n; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VALOR",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // VALOR ::= BOLEAN 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =b; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VALOR",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // VALOR ::= IN LPAREN RPAREN 
            {
              Object RESULT =null;
		 System.out.println("In"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VALOR",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // VALOR ::= ID FUNCION 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 System.out.println("Funcion:" + id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VALOR",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // OPERACION ::= OP EXPRESION 
            {
              Object RESULT =null;
		 System.out.println("operacion y expresion");
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OPERACION",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // OPERACION ::= 
            {
              Object RESULT =null;
		System.out.println("Operacion=null");
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OPERACION",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // OP ::= MULT 
            {
              Object RESULT =null;
		 System.out.println("Mult "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // OP ::= DIV 
            {
              Object RESULT =null;
		System.out.println("Div "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // OP ::= SUMA 
            {
              Object RESULT =null;
		 System.out.println("suma"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // OP ::= RESTA 
            {
              Object RESULT =null;
		 System.out.println("resta "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // OP ::= MAYORQUE 
            {
              Object RESULT =null;
		 System.out.println("Mayorque "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // OP ::= MENORQUE 
            {
              Object RESULT =null;
		  System.out.println("Menorque ");
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // OP ::= MAYORIGU 
            {
              Object RESULT =null;
		 System.out.println("MayorIgual "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // OP ::= MENORIGU 
            {
              Object RESULT =null;
		 System.out.println("Menorigual "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // OP ::= IGUALES 
            {
              Object RESULT =null;
		 System.out.println("Iguales "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // OP ::= NIGUALES 
            {
              Object RESULT =null;
		 System.out.println("No iguales "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // OP ::= OR 
            {
              Object RESULT =null;
		 System.out.println("or "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // OP ::= AND 
            {
              Object RESULT =null;
		 System.out.println("and "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // OP ::= NOT 
            {
              Object RESULT =null;
		 System.out.println("not "); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // FUNCION ::= LPAREN INPARAM RPAREN 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FUNCION",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // INPARAM ::= EXPRESION 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INPARAM",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // INPARAM ::= EXPRESION COMA INPARAM 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INPARAM",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // INPARAM ::= 
            {
              Object RESULT =null;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INPARAM",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
